namespace servos {
    //% block="P0" fixedInstance whenUsed
    export const P0 = new servos.PinServo(pins.P0);
    //% block="P1" fixedInstance whenUsed
    export const P1 = new servos.PinServo(pins.P1);
    //% block="P2" fixedInstance whenUsed
    export const P2 = new servos.PinServo(pins.P2);
    //% block="P3" fixedInstance whenUsed
    export const P3 = new servos.PinServo(pins.P3);
    //% block="C4" fixedInstance whenUsed
    export const C4 = new servos.PinServo(pins.C4);
    //% block="C5" fixedInstance whenUsed
    export const C5 = new servos.PinServo(pins.C5);
    //% block="C6" fixedInstance whenUsed
    export const C6 = new servos.PinServo(pins.C6);
    //% block="C7" fixedInstance whenUsed
    export const C7 = new servos.PinServo(pins.C7);
    //% block="C8" fixedInstance whenUsed
    export const C8 = new servos.PinServo(pins.C8);
    //% block="C9" fixedInstance whenUsed
    export const C9 = new servos.PinServo(pins.C9);
    //% block="C10" fixedInstance whenUsed
    export const C10 = new servos.PinServo(pins.C10);
    //% block="C11" fixedInstance whenUsed
    export const C11 = new servos.PinServo(pins.C11);
    //% block="C12" fixedInstance whenUsed
    export const C12 = new servos.PinServo(pins.C12);
    //% block="C13" fixedInstance whenUsed
    export const C13 = new servos.PinServo(pins.C13);
    //% block="C14" fixedInstance whenUsed
    export const C14 = new servos.PinServo(pins.C14);
    //% block="C15" fixedInstance whenUsed
    export const C15 = new servos.PinServo(pins.C15);
    //% block="C16" fixedInstance whenUsed
    export const C16 = new servos.PinServo(pins.C16);
    //% block="C17" fixedInstance whenUsed
    export const C17 = new servos.PinServo(pins.C17);
    //% block="C18" fixedInstance whenUsed
    export const C18 = new servos.PinServo(pins.C18);
}
